# Generated by Django 4.2.28 on 2026-02-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "warehouse_ID",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("muncipality", models.CharField(max_length=100)),
                ("address_line", models.CharField(max_length=500)),
                ("is_active", models.BooleanField(blank=True, null=True)),
                (
                    "is_location_for_receipts",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "is_location_for_shipments",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "manager_full_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organisation",
                    ),
                ),
            ],
        ),
    ]
