# Generated by Django 4.2.28 on 2026-02-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="warehouse",
            old_name="muncipality",
            new_name="municipality",
        ),
    ]
