# Generated by Django 4.2.28 on 2026-02-16 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_organisation"),
        ("warehouses", "0002_rename_muncipality_warehouse_municipality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.organisation",
            ),
        ),
    ]
